---
- name: Test Infrastructure with pytest
  hosts: localhost
  become: false
  tasks:
    - name: Execute Test for all hosts
      block:
        - name: Install testinfra
          ansible.builtin.shell: 'pip3 install -r requirements.txt'
        - shell: 'pwd'
          register: workdir
        - debug:
            msg: "{{ workdir.stdout }}"
        - shell: 'ls -l'
          register: workdir_list
        - debug:
            msg: "{{ workdir_list.stdout_lines }}"
        - name: Execute Test For all hosts
          ansible.builtin.shell: 'py.test --hosts=ansible://all -v tests/test_myinfra.py'
          register: test_result
          changed_when: no
        - ansible.builtin.debug:
            msg: "{{ test_result.stdout_lines }}"
      rescue:
        - ansible.builtin.debug:
            msg: "{{ test_result.stdout_lines }}"

